spring.application.name=api-gateway
server.port=8080

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

auth.marcacoes-base-url=${AUTH_MARCACOES_BASE_URL:http://localhost:8081}
gateway.marcacoes.base-url=${GATEWAY_MARCACOES_BASE_URL:http://localhost:8081}
gateway.requisicoes.base-url=${GATEWAY_REQUISICOES_BASE_URL:http://localhost:8082}
gateway.requisicoes.ws-base-url=${GATEWAY_REQUISICOES_WS_BASE_URL:ws://localhost:8082}

## Serviço Marcacoes
spring.cloud.gateway.routes[0].id=marcacoes-service
spring.cloud.gateway.routes[0].uri=${gateway.marcacoes.base-url}
spring.cloud.gateway.routes[0].predicates[0]=Path=/marcacoes/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

## Serviço Requisições - WebSocket
spring.cloud.gateway.routes[1].id=requisicoes-ws-service
spring.cloud.gateway.routes[1].uri=${gateway.requisicoes.ws-base-url}
spring.cloud.gateway.routes[1].predicates[0]=Path=/requisicoes/ws/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

## Serviço Requisições - HTTP
spring.cloud.gateway.routes[2].id=requisicoes-service
spring.cloud.gateway.routes[2].uri=${gateway.requisicoes.base-url}
spring.cloud.gateway.routes[2].predicates[0]=Path=/requisicoes/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

## Como exemplo
# spring.cloud.gateway.routes[2].id=servicos-service
# spring.cloud.gateway.routes[2].uri=http://localhost:8083
# spring.cloud.gateway.routes[2].predicates[0]=Path=/servicos/**