# Mongo DB
spring.data.mongodb.database=candidaturas-dev
de.flapdoodle.mongodb.embedded.version=7.0.0

# H2
spring.datasource.url=jdbc:h2:mem:candidaturas-dev;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=test
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Logging
logging.level.pt.florinhas=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG