server.port=8084

# MongoDB
spring.data.mongodb.host=${SPRING_DATA_MONGODB_HOST}
spring.data.mongodb.port=${SPRING_DATA_MONGODB_PORT}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE}
spring.data.mongodb.username=${MONGO_ROOT_USER}
spring.data.mongodb.password=${MONGO_ROOT_PASSWORD}
spring.data.mongodb.authentication-database=${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}

# CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

# Postgres
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# NIF Encryption and Blind Index
app.security.encryption.key=${ENCRYPTION_KEY}
app.security.blindindex.key=${BLIND_INDEX_KEY}

# API Gateway
gateway.shared-secret=${GATEWAY_SHARED_SECRET:}