spring.application.name=marcacoes

# JWT Configuration
jwt.secret=42e2823e8a0e5a01d4d3da2e716ac0126c3f71d14d25919cfd862bbd2de687e1ac0ddfa3d759e7dcac21cd3ce55522f47360488c594d3940e967b9794906463d
jwt.expiration=86400000

# # Database Configuration (example for H2)
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# # H2 Console
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# PostGres Config
spring.datasource.url=jdbc:postgresql://localhost:5432/florinhas
spring.datasource.username=admin
spring.datasource.password=admin123

cors.allowed-origins=http://localhost:5173,http://localhost:3000

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=peidummy2@gmail.com
spring.mail.password=intk hyqs tbbj ikjq 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# NIF.pt Configuration
nif.pt.key=8c3dbc42a02062f14228ef281e7b57aa
nif.pt.url=https://www.nif.pt

# Logging Configuration
# Shows helpful debug info for our own code, but keeps Spring framework quite (INFO)
logging.level.pt.florinhas=DEBUG

# Application Environment Configuration
# development or production
app.environment=development 
app.secure-cookies=true

# File Upload Configuration
app.upload.dir=uploads/documentos
app.upload.max-size=10485760
# Max file size (Spring Boot)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB