spring.application.name=requisicoes

# JWT Configuration
jwt.secret=42e2823e8a0e5a01d4d3da2e716ac0126c3f71d14d25919cfd862bbd2de687e1ac0ddfa3d759e7dcac21cd3ce55522f47360488c594d3940e967b9794906463d
jwt.expiration=86400000

# HikariCP Configuration aka Connection Pool aka More efficient database connections
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000