name: Deploy Frontend to Azure VM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted, ipss-vm]

    steps:
      - name: Deploy Backend Direct on VM
        run: |
          set -e
          # Entrar na pasta do backend e atualizar o código
          cd /home/florinhasuser/ipss-digital/platform-backend
          git fetch origin
          git reset --hard origin/main

          # Reconstruir a app
          docker compose up -d --build
          
          # Limpeza de imagens antigas
          docker image prune -f